"""Pure, host-independent MayaCraft domain models."""

from MayaCraft.domain.character import CharacterSnapshot, NodeSummary, RigNode
from MayaCraft.domain.change import AttributeChange, ChangeReceipt, CharacterRegistrationPlan
from MayaCraft.domain.canvas import ProjectedRigNode, hit_test, project_rig_nodes
from MayaCraft.domain.session import CharacterSession, SessionCharacter
from MayaCraft.domain.rig_health import RigHealthReport, RigModuleHealth, analyze_rig, focus_rig_nodes
from MayaCraft.domain.deformation import (
    DeformationInspectorReport,
    DeformationMRIResult,
    DeformationRepairPlan,
    DeformationRepairReceipt,
    DeformationReport,
    InfluenceWeightDiagnostic,
    VertexWeightSignal,
    WeightVectorChange,
    analyze_influence_rows,
    analyze_weight_rows,
    merge_influence_reports,
    plan_normalization_repair,
)
from MayaCraft.domain.motion import (
    ContactInterval,
    AnchorCorrection,
    ContactAnchorPlan,
    ContactAnchorReceipt,
    MotionAnalysis,
    MotionCapture,
    MotionComparison,
    MotionComparisonSignal,
    MotionSample,
    MotionSignal,
    analyze_motion,
    compare_motion,
    plan_contact_anchor,
)
from MayaCraft.domain.rig_graph import (
    ObservedRigBehavior,
    ObservedRigNode,
    RigBehaviorSpec,
    RigBuildChange,
    RigBuildPlan,
    RigBuildReceipt,
    RigConnectionSpec,
    RigGraphIssue,
    RigGraphSpec,
    RigModuleSpec,
    RigNodeSpec,
    RigSocketSpec,
    compile_incremental_rig,
    compute_pole_vector_position,
    bind_graph_to_skeleton,
    golden_biped_graph,
    module_build_order,
    validate_rig_graph,
)
from MayaCraft.domain.skeleton import JointObservation, SemanticJoint, SkeletonAnalysis, SkeletonIssue, analyze_skeleton
from MayaCraft.domain.skin_mirror import (
    InfluenceObservation, InfluenceMirrorIssue, InfluenceMirrorMap, InfluenceMirrorPair,
    SkinMirrorChange, SkinMirrorPlan, SkinMirrorReceipt, SkinVertexObservation,
    build_influence_mirror_map, plan_skin_mirror,
)
from MayaCraft.domain.deformation_space import (
    DeformationFieldProjection, SpatialVertexSignal, hit_test_spatial,
    project_deformation_field, vertices_in_brush,
)
from MayaCraft.domain.pose_clip import (
    ClipAsset, PoseAsset, PoseDifference, PoseFrame, PoseNode,
    blend_pose_frames, clip_asset_from_dict, clip_asset_to_dict,
    compare_pose_frames, pose_asset_from_dict,
    pose_asset_to_dict, validate_clip, validate_pose_frame,
)
from MayaCraft.domain.retarget import (
    RetargetAxisTemplate,
    RetargetClipFrameSignal, RetargetClipPreview, RetargetContactDiagnostic,
    RetargetJointMapping, RetargetLayerKey, RetargetLayerPlan, RetargetLayerReceipt,
    RetargetPosePreview, RetargetPreviewSignal, RetargetProfile,
    RetargetResultValidation, RetargetValidationSignal,
    build_retarget_profile, plan_retarget_layer, preview_retarget_clip,
    preview_retarget_pose, retarget_axis_templates, validate_retarget_axis_template,
    validate_retarget_result, with_retarget_axis_template,
)
from MayaCraft.domain.ik import (
    ContactIKAnchorTarget, ContactIKLayerKey, ContactIKLayerPlan, ContactIKLayerReceipt,
    ContactIKSample, ContactIKSettings, FabrikResult, PelvisCompensation,
    RetargetContactIKPreview, RootGroundCorrection,
    plan_contact_ik_layer, preview_retarget_contact_ik, solve_fabrik,
)
from MayaCraft.domain.clip_package import (
    ClipPackage, clip_package_from_dict, clip_package_to_dict,
    remap_clip_package_paths, validate_clip_package,
)
from MayaCraft.domain.clip_library import (
    ClipLibraryEntry, ClipPackagePreflight, build_clip_library_entry,
    filter_clip_library_entries, preflight_clip_package,
)
from MayaCraft.domain.rig_switching import (
    FKIKMatchPlan, FKIKMatchReceipt, RigMatchTarget, RigSwitchIssue,
    RigTransformSample, SpaceSwitchPlan, SpaceSwitchReceipt,
    maximum_matrix_error, maximum_position_error, plan_fk_ik_match,
    plan_space_switch, transform_fingerprint,
)

__all__ = [
    "AttributeChange",
    "ChangeReceipt",
    "CharacterRegistrationPlan",
    "CharacterSnapshot",
    "NodeSummary",
    "ProjectedRigNode",
    "RigNode",
    "RigHealthReport",
    "RigModuleHealth",
    "analyze_rig",
    "focus_rig_nodes",
    "DeformationMRIResult",
    "DeformationInspectorReport",
    "DeformationReport",
    "InfluenceWeightDiagnostic",
    "VertexWeightSignal",
    "analyze_influence_rows",
    "analyze_weight_rows",
    "merge_influence_reports",
    "DeformationRepairPlan",
    "DeformationRepairReceipt",
    "WeightVectorChange",
    "plan_normalization_repair",
    "ContactInterval",
    "AnchorCorrection",
    "ContactAnchorPlan",
    "ContactAnchorReceipt",
    "MotionAnalysis",
    "MotionCapture",
    "MotionComparison",
    "MotionComparisonSignal",
    "MotionSample",
    "MotionSignal",
    "analyze_motion",
    "compare_motion",
    "plan_contact_anchor",
    "ObservedRigNode",
    "ObservedRigBehavior",
    "RigBehaviorSpec",
    "RigBuildChange",
    "RigBuildPlan",
    "RigBuildReceipt",
    "RigConnectionSpec",
    "RigGraphIssue",
    "RigGraphSpec",
    "RigModuleSpec",
    "RigNodeSpec",
    "RigSocketSpec",
    "compile_incremental_rig",
    "compute_pole_vector_position",
    "bind_graph_to_skeleton",
    "golden_biped_graph",
    "module_build_order",
    "validate_rig_graph",
    "JointObservation",
    "SemanticJoint",
    "SkeletonAnalysis",
    "SkeletonIssue",
    "analyze_skeleton",
    "InfluenceObservation",
    "InfluenceMirrorIssue",
    "InfluenceMirrorMap",
    "InfluenceMirrorPair",
    "build_influence_mirror_map",
    "SkinMirrorChange",
    "SkinMirrorPlan",
    "SkinMirrorReceipt",
    "SkinVertexObservation",
    "plan_skin_mirror",
    "DeformationFieldProjection",
    "SpatialVertexSignal",
    "hit_test_spatial",
    "project_deformation_field",
    "vertices_in_brush",
    "hit_test",
    "project_rig_nodes",
    "ClipAsset",
    "PoseAsset",
    "PoseDifference",
    "PoseFrame",
    "PoseNode",
    "blend_pose_frames",
    "clip_asset_from_dict",
    "clip_asset_to_dict",
    "compare_pose_frames",
    "pose_asset_from_dict",
    "pose_asset_to_dict",
    "validate_clip",
    "validate_pose_frame",
    "RetargetJointMapping",
    "RetargetAxisTemplate",
    "RetargetClipFrameSignal",
    "RetargetClipPreview",
    "RetargetContactDiagnostic",
    "RetargetLayerKey",
    "RetargetLayerPlan",
    "RetargetLayerReceipt",
    "RetargetPosePreview",
    "RetargetPreviewSignal",
    "RetargetProfile",
    "RetargetResultValidation",
    "RetargetValidationSignal",
    "build_retarget_profile",
    "plan_retarget_layer",
    "preview_retarget_clip",
    "preview_retarget_pose",
    "retarget_axis_templates",
    "validate_retarget_axis_template",
    "validate_retarget_result",
    "with_retarget_axis_template",
    "ContactIKSample",
    "ContactIKSettings",
    "ContactIKAnchorTarget",
    "ContactIKLayerKey",
    "ContactIKLayerPlan",
    "ContactIKLayerReceipt",
    "FabrikResult",
    "PelvisCompensation",
    "RetargetContactIKPreview",
    "RootGroundCorrection",
    "plan_contact_ik_layer",
    "preview_retarget_contact_ik",
    "solve_fabrik",
    "ClipPackage",
    "clip_package_from_dict",
    "clip_package_to_dict",
    "remap_clip_package_paths",
    "validate_clip_package",
    "ClipLibraryEntry",
    "ClipPackagePreflight",
    "build_clip_library_entry",
    "filter_clip_library_entries",
    "preflight_clip_package",
    "FKIKMatchPlan",
    "FKIKMatchReceipt",
    "RigMatchTarget",
    "RigSwitchIssue",
    "RigTransformSample",
    "SpaceSwitchPlan",
    "SpaceSwitchReceipt",
    "maximum_matrix_error",
    "maximum_position_error",
    "plan_fk_ik_match",
    "plan_space_switch",
    "transform_fingerprint",
]
